### ISSUE TITLE
(very minor issue) Missing decimal point in filter function?

### ISSUE THREAD

**Issue by shiaki** [ZwickyTransientFacility/ztf-avro-alert#2]
https://github.com/ZwickyTransientFacility/ztf-avro-alert/blob/69a156be324d6f93e59385a83090f264945895c5/notebooks/Filtering_alerts.ipynb#L188

As per the official recommendation at https://zwickytransientfacility.github.io/ztf-avro-alert/filtering.html, the cut on `elong` might be `elong < 1.2`

This potential issue was identified when I try to compare the results of this filter function with my own.

**Comment by ebellm** [comment]
Thanks!
