### ISSUE TITLE
Nullable schema fields should list "null" first in the union

### ISSUE THREAD

**Issue by ebellm** [ZwickyTransientFacility/ztf-avro-alert#6]
Many of the fields in our Avro alert schemas are default null. However, the schemas list "null" as the second allowed data type in the union, which is [not allowed by the Avro spec](https://avro.apache.org/docs/current/spec.html#Unions):

> Note that when a default value is specified for a record field whose type is a union, the type of the default value must match the first element of the union. Thus, for unions containing "null", the "null" is usually listed first, since the default value of such unions is typically null.

**Comment by spenczar** [comment]
I ran into this myself. This would be really good to fix for interoperability with Avro tools.

**Comment by ebellm** [comment]
updated in #9.
